<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHt1jLzb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHt1jLzb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHt1jLzb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHt1jLzb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHt1jLzb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ht1jLzb',
    'container.build_id' => 'fabed7d9',
    'container.build_time' => 1733326771,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHt1jLzb');
