<?php

namespace ContainerP12FsrF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllershowTaskService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7ygAW3n.App\Controller\TaskController::show_task()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7ygAW3n.App\\Controller\\TaskController::show_task()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'taskRepository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'taskRepository' => 'App\\Repository\\TaskRepository',
            'serializer' => '?',
        ]))->withContext('App\\Controller\\TaskController::show_task()', $container);
    }
}
