<?php

namespace ContainerQ4BwiAY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EcGx8xcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ecGx8xc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ecGx8xc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\TaskController::create_task' => ['privates', '.service_locator.Pvsz2ki.App\\Controller\\TaskController::create_task()', 'getTaskControllercreateTaskService', true],
            'App\\Controller\\TaskController::update_task' => ['privates', '.service_locator.LlFsD3l.App\\Controller\\TaskController::update_task()', 'getTaskControllerupdateTaskService', true],
            'App\\Controller\\TaskController::delete_task' => ['privates', '.service_locator.LlFsD3l.App\\Controller\\TaskController::delete_task()', 'getTaskControllerdeleteTaskService', true],
            'App\\Controller\\TaskController::show_task' => ['privates', '.service_locator.HTuWMbh.App\\Controller\\TaskController::show_task()', 'getTaskControllershowTaskService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\TaskController:create_task' => ['privates', '.service_locator.Pvsz2ki.App\\Controller\\TaskController::create_task()', 'getTaskControllercreateTaskService', true],
            'App\\Controller\\TaskController:update_task' => ['privates', '.service_locator.LlFsD3l.App\\Controller\\TaskController::update_task()', 'getTaskControllerupdateTaskService', true],
            'App\\Controller\\TaskController:delete_task' => ['privates', '.service_locator.LlFsD3l.App\\Controller\\TaskController::delete_task()', 'getTaskControllerdeleteTaskService', true],
            'App\\Controller\\TaskController:show_task' => ['privates', '.service_locator.HTuWMbh.App\\Controller\\TaskController::show_task()', 'getTaskControllershowTaskService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\TaskController::create_task' => '?',
            'App\\Controller\\TaskController::update_task' => '?',
            'App\\Controller\\TaskController::delete_task' => '?',
            'App\\Controller\\TaskController::show_task' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\TaskController:create_task' => '?',
            'App\\Controller\\TaskController:update_task' => '?',
            'App\\Controller\\TaskController:delete_task' => '?',
            'App\\Controller\\TaskController:show_task' => '?',
        ]);
    }
}
