<?php

namespace ContainerHt1jLzb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskControllerdeleteTaskService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LlFsD3l.App\Controller\TaskController::delete_task()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LlFsD3l.App\\Controller\\TaskController::delete_task()'] = ($container->privates['.service_locator.LlFsD3l'] ?? $container->load('get_ServiceLocator_LlFsD3lService'))->withContext('App\\Controller\\TaskController::delete_task()', $container);
    }
}
